//! 型定義生成コマンド

use std::fs;
use std::path::Path;

use anyhow::{Context, Result};
use gear_mesh_generator::TypeScriptGenerator;

use crate::config::Config;

/// 型定義を生成
pub fn run(input_dir: &Path, output_dir: &Path, config: &Config) -> Result<()> {
    println!("Generating TypeScript definitions...");
    println!("  Input: {}", input_dir.display());
    println!("  Output: {}", output_dir.display());

    // 出力ディレクトリを作成
    fs::create_dir_all(output_dir).context("Failed to create output directory")?;

    // TODO: 実際の実装では、Rustソースファイルを解析してGearMeshTypeを抽出する
    // 現在はプレースホルダー

    // サンプル出力を生成
    let generator_config = config.to_generator_config();
    let mut generator = TypeScriptGenerator::new(generator_config);

    // デモ用の空の型リスト
    let types = Vec::new();
    let output = generator.generate(&types);

    // ヘッダーコメントを追加
    let header = format!(
        r#"// This file was auto-generated by gear-mesh
// Do not edit this file manually
// Generated at: {}

"#,
        chrono_lite::Datetime::now(),
    );

    let final_output = format!("{}{}", header, output);

    // ファイルに書き込み
    let output_file = output_dir.join(&config.output_file);
    fs::write(&output_file, final_output).context("Failed to write output file")?;

    println!("Generated: {}", output_file.display());
    println!("Done!");

    Ok(())
}

// シンプルな日時取得（外部クレートなし）
mod chrono_lite {
    use std::time::{SystemTime, UNIX_EPOCH};

    pub struct Datetime {
        timestamp: u64,
    }

    impl Datetime {
        pub fn now() -> Self {
            let timestamp = SystemTime::now()
                .duration_since(UNIX_EPOCH)
                .unwrap()
                .as_secs();
            Self { timestamp }
        }
    }

    impl std::fmt::Display for Datetime {
        fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
            // Unix timestamp to ISO 8601 (簡易版)
            write!(f, "{}", self.timestamp)
        }
    }
}
